services:
  - type: web
    name: rental-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: your-database-url-here
    healthCheckPath: /
    autoDeploy: true 